### ISSUE TITLE
System process died but concierge still working and can't stop via MS service console (had to kill it)

### ISSUE THREAD

**Issue by agend** [qoollo/Concierge#13]
It ate 1G of RAM and 10% of CPU
but don't have open any port our service use

**Comment by agend** [comment]
Probably service was in start state

**Comment by slmjy** [comment]
@agend so the scenario is: kill the service process and then try to stop service via service management console?

**Comment by agend** [comment]
1) Service was stopped.
2) Service was started
3) At start it perform long running check
4) I tried to stop it during this check
