### ISSUE TITLE
Change defult port to something other than 8000

### ISSUE THREAD

**Issue by slmjy** [qoollo/Concierge#6]
Это, например, дефолтный порт для django сервера. 9000 - для uwsgi. 3000 - для Ruby. Надо выбрать какой-нибудь не круглый. Я сам сделаю, все равно буду немного concierge дорабатывать на днях.

**Comment by slmjy** [comment]
Or add an easy way to change port without adding whole wcf configuration to config.

**Comment by nmenshov** [comment]
Change to 9070)) it is free now
